import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LocomotiveScrollContainer from './loco/Loco'
import LiveChat from './component/live-chat/LiveChat'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <LiveChat></LiveChat>
        <LocomotiveScrollContainer>
        {children}
          
        </LocomotiveScrollContainer>
      
      </body>
    </html>
  )
}
